---
output: html_document
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse   = TRUE,
  warning    = FALSE,
  message    = FALSE,
  comment    = "#>",
  fig.path   = "man/figures/",
  fig.retina = 3
)
```

# Welcome to our survey!

Welcome and thank you for your interest in our survey! The purpose of this survey is to develop a quantitative model of consumer choice to inform the design decisions of a COVID vaccine policy. This study is being conducted at The George Washington University as part of a research effort. You must be a resident of the United States above the age of 18 and who has not received a dose of a COVID-19 vaccine to partake in this survey.

This survey involves questions that ask whether a certain condition would result in you receiving the COVID-19 vaccine. These conditions can be seen as positive, negative, or neutral. These conditions will not actually occur and you will not need to take a COVID-19 vaccine based on your answers in this survey. All responses will be used purely for educational purposes. A type of question you may see would be the following: "Will you take a COVID-19 vaccine if given door-to-door?" This question is asking if you would take a COVID-19 vaccine if you had the option to take it at your doorstep. You may answer "Yes" or "No" to this question. At the end of the survey we will be collecting demographic information (such as income and age) that will also be used purely for educational purposes. These demographic attributes will especially help us account for bias in our data: 

- Race/ethnicity: data suggests that marginalized races may have a sense of mistrust in the American healthcare system, stemming from mistreatment to microaggressions towards these groups from practitioners. Collecting data from every ethic group allows us to compare the level of trust towards vaccines and infer it on COVID vaccination rates. 
- Political beliefs: conversations around COVID-19 have become increasingly political. We would like to gather data from people of all political beliefs to see the relationship between politics and the COVID vaccine. 
- Income: data suggests that people of lower income also are subjected to mistreatment and microaggressions by healthcare practitioners, also hampering trust in our healthcare system. Collecting data from various income groups also allows us to compare the level of trust towards vaccines and infer it on COVID vaccination rates.

If you have any questions about this survey, then please contact marketingvaccinepolicy@gmail.com.

---

# Consent form

This survey is being conducted by students at The George Washington University. We will not be collecting any identifying data, such as your name or address. The whole survey will take approximately 10 to 15 minutes to complete. Your participation is voluntary and you may stop the survey at any time.

If you are eligible to and would like to participate, please answer the following questions:

I am age 18 or older.

- Yes
- No

I have not received a dose of a COVID-19 vaccine.

- Yes
- No

I have read and understand the above information. 

- Yes
- No
