---
output: html_document
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse   = TRUE,
  warning    = FALSE,
  message    = FALSE,
  comment    = "#>",
  fig.path   = "man/figures/",
  fig.retina = 3
)
```


# Welcome to our survey!

Welcome and thank you for your interest in our survey! The purpose of this survey is to develop a quantitative model of consumer choice to inform the design decisions of a COVID vaccine policy. This survey is being conducted for a research initiative at The George Washington University. You must be a resident of the United States above the age of 18 and who has not received a dose of a COVID-19 vaccine to partake in this survey. You must also not have a health condition or disability that prevents you from being eligible to take the COVID-19 vaccine. 

This survey involves questions that ask whether a certain policy would result in you receiving the COVID-19 vaccine. These policies vary across attributes and can be seen as positive, negative, or neutral. These policies are still hypothetical and you will not need to take a COVID-19 vaccine based on your answers in this survey. At the end of the survey we will be collecting demographic information. These demographic attributes will especially help us account for bias in our data.

--- 
# Consent and Eligibility

Your participation in this survey is voluntary. You may choose not to participate. If you decide to participate in this survey, you may withdraw at any time with no penalty. All responses will be used solely for academic purposes. Your responses will be confidential and we will not collect or share any identifying data such as your name or address.

The whole survey will take approximately 10 to 15 minutes to complete. Your participation is voluntary and you may stop the survey at any time. If you are eligible to and would like to participate, please answer the following questions:

I am 18 years of age or older.

- Yes
- No

I have not received any doses of a COVID-19 vaccine.

- Yes
- No

I do not have a disability or health condition that prevents me from being able to take the COVID-19 vaccine.

- Yes
- No

I have read and understand the above information. 

- Yes
- No
